// utils/mockData.ts

import { Provider, Ticket, Seller } from "../types";

export const mockProviders: Provider[] = [
  {
    id: 1,
    name: "Водоканал-Сервис",
    address: "ул. Водная, д. 15",
    resource: "Вода",
    available: 50,
    price: 150,
    rating: 4.8,
    status: "active",
    workTime: "08:00 - 20:00",
    coordinates: { lat: 55.75, lng: 37.61 },
    phone: "+7 (999) 111-22-33",
    email: "info@vodakanal.ru",
  },
  {
    id: 2,
    name: "Энерго-Центр",
    address: "пр. Энергетиков, д. 7",
    resource: "Электричество",
    available: 30,
    price: 200,
    rating: 4.5,
    status: "active",
    workTime: "09:00 - 18:00",
    coordinates: { lat: 55.76, lng: 37.62 },
    phone: "+7 (999) 222-33-44",
    email: "info@energo.ru",
  },
  {
    id: 3,
    name: "Газ-Снаб",
    address: "ул. Газовая, д. 3",
    resource: "Газ",
    available: 20,
    price: 300,
    rating: 4.2,
    status: "blocked",
    workTime: "10:00 - 17:00",
    coordinates: { lat: 55.74, lng: 37.6 },
    phone: "+7 (999) 333-44-55",
    email: "info@gaz.ru",
  },
  {
    id: 4,
    name: "Тепло-Сервис",
    address: "ул. Теплая, д. 12",
    resource: "Тепло",
    available: 15,
    price: 250,
    rating: 4.7,
    status: "active",
    workTime: "08:30 - 19:30",
    coordinates: { lat: 55.77, lng: 37.63 },
    phone: "+7 (999) 444-55-66",
    email: "info@teplo.ru",
  },
  {
    id: 5,
    name: "Чистая Вода",
    address: "ул. Родниковая, д. 8",
    resource: "Вода",
    available: 40,
    price: 120,
    rating: 4.9,
    status: "active",
    workTime: "07:00 - 22:00",
    coordinates: { lat: 55.73, lng: 37.58 },
    phone: "+7 (999) 555-66-77",
    email: "info@water.ru",
  },
  {
    id: 6,
    name: "Эко-Энергия",
    address: "ул. Зеленая, д. 21",
    resource: "Электричество",
    available: 25,
    price: 180,
    rating: 4.6,
    status: "active",
    workTime: "08:00 - 20:00",
    coordinates: { lat: 55.78, lng: 37.65 },
    phone: "+7 (999) 666-77-88",
    email: "info@ecoenergy.ru",
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 101,
    userName: "Иван Петров",
    resource: "Вода",
    status: "active",
    issueDate: "2024-01-15",
    expiryDate: "2024-02-15",
    provider: "Водоканал-Сервис",
    quantity: 2,
  },
  {
    id: 102,
    userName: "Сергей Иванов",
    resource: "Электричество",
    status: "pending",
    issueDate: "2024-01-20",
    expiryDate: "2024-02-20",
    provider: "Энерго-Центр",
    quantity: 1,
  },
  {
    id: 103,
    userName: "Анна Сидорова",
    resource: "Газ",
    status: "expired",
    issueDate: "2023-12-10",
    expiryDate: "2024-01-10",
    provider: "Газ-Снаб",
    quantity: 3,
  },
  {
    id: 104,
    userName: "Петр Смирнов",
    resource: "Тепло",
    status: "active",
    issueDate: "2024-01-18",
    expiryDate: "2024-02-18",
    provider: "Тепло-Сервис",
    quantity: 1,
  },
  {
    id: 105,
    userName: "Ольга Новикова",
    resource: "Вода",
    status: "pending",
    issueDate: "2024-01-22",
    expiryDate: "2024-02-22",
    provider: "Чистая Вода",
    quantity: 2,
  },
  {
    id: 106,
    userName: "Дмитрий Козлов",
    resource: "Электричество",
    status: "active",
    issueDate: "2024-01-10",
    expiryDate: "2024-02-10",
    provider: "Эко-Энергия",
    quantity: 1,
  },
];

export const mockSellers: Seller[] = [
  {
    id: 1,
    name: "Алексей Смирнов",
    email: "alexey@vodakanal.ru",
    resource: "Вода",
    status: "active",
    address: "ул. Водная, д. 15",
    phone: "+7 (999) 111-22-33",
    rating: 4.8,
    ticketsIssued: 156,
  },
  {
    id: 2,
    name: "Елена Петрова",
    email: "elena@energo.ru",
    resource: "Электричество",
    status: "active",
    address: "пр. Энергетиков, д. 7",
    phone: "+7 (999) 222-33-44",
    rating: 4.5,
    ticketsIssued: 89,
  },
  {
    id: 3,
    name: "Михаил Иванов",
    email: "mikhail@gaz.ru",
    resource: "Газ",
    status: "blocked",
    address: "ул. Газовая, д. 3",
    phone: "+7 (999) 333-44-55",
    rating: 4.2,
    ticketsIssued: 45,
  },
  {
    id: 4,
    name: "Наталья Сидорова",
    email: "natalia@teplo.ru",
    resource: "Тепло",
    status: "active",
    address: "ул. Теплая, д. 12",
    phone: "+7 (999) 444-55-66",
    rating: 4.7,
    ticketsIssued: 234,
  },
  {
    id: 5,
    name: "Константин Новиков",
    email: "konstantin@water.ru",
    resource: "Вода",
    status: "active",
    address: "ул. Родниковая, д. 8",
    phone: "+7 (999) 555-66-77",
    rating: 4.9,
    ticketsIssued: 312,
  },
];

// Вспомогательные функции
export const getProviderById = (id: number): Provider | undefined => {
  return mockProviders.find((provider) => provider.id === id);
};

export const getTicketsByStatus = (status: Ticket["status"]): Ticket[] => {
  return mockTickets.filter((ticket) => ticket.status === status);
};

export const getSellersByStatus = (status: Seller["status"]): Seller[] => {
  return mockSellers.filter((seller) => seller.status === status);
};
